import { AbsoluteFill, Img, staticFile, useCurrentFrame, useVideoConfig, interpolate } from "remotion";

interface CinematicSceneProps {
  imageSrc: string;
  overlayText?: string;
  rtl?: boolean;
}

/*
 * This video was generated by AI.
 * The original video assets were replaced with extracted still frames
 * to improve preview reliability in Remotion.
 */
import { AbsoluteFill, Img, staticFile, useCurrentFrame, useVideoConfig, interpolate } from "remotion";

interface CinematicSceneProps {
  imageSrc: string;
  overlayText?: string;
  rtl?: boolean;
}

export const CinematicScene: React.FC<CinematicSceneProps> = ({ imageSrc, overlayText, rtl }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Ken Burns effect parameters. The duration is set to 12 seconds, assuming this is the default length for a scene.
  // This value will be managed by the Sequence component in Composition.tsx for specific scene timings.
  const DURATION_PER_SCENE = 12 * fps; 
  
  const zoom = interpolate(frame, [0, DURATION_PER_SCENE], [1, 1.15]);
  const panX = interpolate(frame, [0, DURATION_PER_SCENE], [-0.05, 0.05]); // Pan left to right
  const panY = interpolate(frame, [0, DURATION_PER_SCENE], [-0.05, 0.05]); // Pan up to down

  const imageStyle = {
    width: "100%",
    height: "100%",
    objectFit: "cover" as const,
    transform: `scale(${zoom}) translate(${panX * 100}%, ${panY * 100}%)`,
  };

  return (
    <AbsoluteFill>
      {/* Replace Video with Img and apply Ken Burns effect */}
      <Img
        src={staticFile(imageSrc)}
        style={imageStyle}
      />
      {/* Gradient overlay for readability */}
      <AbsoluteFill style={{ 
        background: "linear-gradient(to bottom, rgba(0,0,0,0.3), rgba(0,0,0,0.6))",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        color: "white",
        fontSize: "48px",
        textAlign: rtl ? "right" : "center",
        direction: rtl ? "rtl" : "ltr",
        padding: "0 100px"
      }}>
        {overlayText && <div>{overlayText}</div>}
      </AbsoluteFill>
    </AbsoluteFill>
  );
};
